version: '3'

services:
  hunt-analyzer:
    # Public image from GitHub Container Registry
    image: ghcr.io/aidenmitchell/hunt-analyzer:main
    container_name: hunt-analyzer
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      # Environment variables with explicit syntax for better Portainer compatibility
      SUBLIME_API_TOKEN: "${SUBLIME_API_TOKEN:-}"
      SECRET_KEY: "${SECRET_KEY:-change_this_to_a_random_string}"